### ISSUE TITLE
Generating unusual output by specifying a region.

### ISSUE THREAD

**Issue by observer2735** [google/deepvariant#697]
Hi,

I'm tring to test Deepvariant in my own panel data and set --regins to the interest regin, but something happend in my output. I provided reference gene hg19 and index it with samtools index, and provided .bam file with index named .bam.bai, when i run following commend, it's can work and create files :

        BIN_VERSION="1.5.0"
        
        INPUT_DIR="${PWD}/test_input"
        OUTPUT_DIR="${PWD}/test_output"
        mkdir -p "${OUTPUT_DIR}"
        
        docker run \
          -v "${INPUT_DIR}":"/input" \
          -v "${OUTPUT_DIR}":"/output" \
          google/deepvariant:"${BIN_VERSION}" \
          /opt/deepvariant/bin/run_deepvariant \
          --model_type=WGS \
          --ref=/input/ucsc.hg19.fasta \
          --reads=/input/my_test.bam \
          --regions chx:xxxxx-xxxxxx \
          --output_vcf=/output/output.vcf.gz \
          --output_gvcf=/output/output.g.vcf.gz \
          --num_shards=1 \

The following figure is my question: when i run the test files provided by Deepvariant, it can work rightly, but if i run it on my own dataset, it create this .html file:
![image](https://github.com/google/deepvariant/assets/139957165/9fd3f9d2-9a33-4aa1-a7b8-d54d75af7163)
I checked the Depth item in the website, it's 1091, and I use command "samtools view xxxx | wc -l" it prints 1174, so maybe Deepvariant recognize all reads and count them rightly , but why it doesn't output right indel, genotypes and other items? Why they are empyt?

**Comment by pgrosu** [comment]
Hi @observer2735,

So your depth is very high, which either indicates that you are trying to measure something with very low VAF (which this is not the case with a value of 0.4), or you might have duplicated parts of the genome or are working with very small genomic region.  Now having said that, you could try down-sampling your region to something along the lines of 80-100, and see if the call changes.  Keep in mind, the pileup images for DeepVariant are ~100 reads, so it will randomly down-sample from the reads to fit into the maximum of the allowed pileup image.  

You seem to have one call that was rejected, meaning a RefCall entry of a proposed candidate but rejected as non-variant by the model, and then uncalled (`./.`) because your GQ is less than 20.  Your QUAL is 0, indicating there is no variant there.  Your GQ is around 11-12, which this is just a RefCall based on the model.  The reason your read depth (DP) is smaller than the number of rows you are counting might be that it locally realigned the reads, and then the allele counter got a different number for the DP given a different number of supporting reads.  Probably looking at your BAM in IGV might help to confirm.  Also aligning to [GRCh38 without ALT contigs](https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta.gz) might also be a better option to try than hg19 for generating the BAM files, and then also using that as a reference in DeepVariant -- as DeepVariant assumes the same reference was used during the mapping when generating the BAM files.

Hope it helps,
Paul

**Comment by observer2735** [comment]
Hi Paul,

Thank you very much for responding to my questions and providing detailed explanations, and it's give me some very import tips tha I ignore before, so very appreciate for your reply.

A few hours ago I tried to change command --regions chx:xxxxx-xxxxxx to --regions chx, deleted the locations of rigion and it output excepted files. But somethings confused me again, for example, my research topic is about repeat times in the NGS data, and my original intention in using Deepvariant is to detect the sequencing noise and delete them or find the true data in noised data. However ,what I saw is that the Deepvariant only can print one mutation such like following string:

chx   xxxxxx          .	TAAA	T	1.6	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:5:490:36,81:0.165306:0,3,25

This is very contrary to common sense, because in this loci it have at least 490 reads to cover it (it maybe more because Deepvariant can't recognize all reads due to empty align), Deepvariant only give one mutation that is TAAA to T, but when I open IGV to focus on the loci, it shows that they are more than one mutation, in fact, it's far more than one mutation.

I mentioned in the previous paragraph that I am very grateful for your reply because you give me one tip is that :" Keep in mind, the pileup images for DeepVariant are ~100 reads, so it will randomly down-sample from the reads to fit into the maximum of the allowed pileup image." So I think maybe what confuse me is that Deepvariant only can detect 100x depth data? or somethings else I can do to detect truth sequence data in NGS data?

Very sorry to bother you, wish you a pleasant work and life,
Ji

**Comment by pgrosu** [comment]
Hi Ji,

Glad it was helpful, and no bother at all -- this is fun for me :)  Now there are a few things going on here to better understand what DeepVariant might be seeing:

$`1)`$ The first thing is to get a BAM of your realigned reads for that region.  To do that, just add the following to your script (below `--num_shards=1`):

```
--make_examples_extra_args="emit_realigned_reads=true,realigner_diagnostics=/output/realigned_reads
```

as described in the [FAQ section](https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md#what-is-the-realigner-and-how-does-it-work) or in the [following comment](https://github.com/google/deepvariant/issues/691#issuecomment-1662968609).  Make sure to create the `realigned_reads` directory first, by adding the following line to your script, below your first `mkdir` statement:

`mkdir -p "${OUTPUT_DIR}/realigned_reads"` 

After you relaunch the script, the BAM file(s) representing that region would be the one you would use in IGV.

$`2)`$ Now given that, there would still be a lot of reads in that region for the allele counter to create candidates from.  You have below the 1,500 maximum read depth, as noted in the following [FAQ section](https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md#how-are-ad-and-dp-values-calculated), but quite a few seem to still remain.  You noticed that only 490 appear supporting that position, and DeepVariant is position-specific.  If the quality of the allele is low those are not used.  For example, your GQ here is 5 to support the variant, and your QUAL 1.5, which tells me there is no variant and the error is 32% of it being that variant.  It would also help to check your gVCF as that contains everything.  Also if there are multiple deletions at the same location it determines the deletions with the highest read support, and deletes all other deletions from the allele map.

$`4)`$ There are additional cutoffs for the type of candidates it selects.  If you want to filter in low depth candidates, you can adjust this via the `--make_examples_extra_args=`, by setting some or all of the following parameters to your preference (notice the the default count is already 2, which you are obvserving):

* vsc_min_count_snps (the default is 2)
* vsc_min_count_indels (the default is 2)
* vsc_min_fraction_snps (the default is 0.12)
* vsc_min_fraction_indels (the default is 0.06)
* vsc_min_fraction_multiplier (the default is 1.0)

Here is an example:

```
--make_examples_extra_args='vsc_min_count_snps=3,vsc_min_count_indels=3,vsc_min_fraction_snps=0.12,vsc_min_fraction_indels=0.06'
```

You can read more details about these parameters at the following links:

https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data

https://github.com/google/deepvariant/blob/r1.5/deepvariant/make_examples_options.py#L178-L202

$`4)`$ Now regarding the pileup, that basically is used to generate the GT and GQ values from a trained model.  So DeepVariant first picks candidates by going through the regions of the genome you specify, and are also in your BAM file.  Now given those candidates, it then picks data from your reads of roughly ~100 positions on each side of your variant (actually it is 199) to build an image to run through the prediction model.  Information that is collected for building that image, is things such as the read base, base quality, if the read supports the variant, etc., all which you can read in [the following blog](https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/).  For each of these pieces of information it can only fit 100 rows of it, as the model operates optimally with only a height of ~100, and was trained as such.  So the model is only used to infer your GT with the supporting GQ, as the candidates are already selected before it even gets to the prediction portion of DeepVariant. 

$`5)`$  Since you're trying to find the true candidates among noisy data, you have the option of running known truth candidates with different gradations of noise to determine what your parameters and thresholds for those parameters should be.  Some of that could be done with some preprocessing of your BAM files or reads, if you know specific parameters that your data should exhibit.  Regarding truth candidates, you can look at the list of samples that were used to train DeepVariant:

https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-details-training-data.md

Given those samples you can simulate or vary the reads to determine the effect on the prediction of known variants, where you would also explore the parameter space for optimization.  You can look at a sample training example to get an idea how they were used to train a model:

https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-training-case-study.md

This becomes very complex, as you will need to do a lot of validation.

Hope it helps,
Paul

**Comment by MariaNattestad** [comment]
@observer2735 Can you say more about what you are trying to do? Is it germline variant calling? Or maybe counting all the errors in the reads?
Please elaborate, thank you!
Maria

**Comment by AndrewCarroll** [comment]
Hi @observer2735 

I will second Maria's question about the application you are trying to do.

I did want to mention one things about your statement

```
This is very contrary to common sense, because in this loci it have at least 490 reads to cover it (it maybe more because Deepvariant can't recognize all reads due to empty align), Deepvariant only give one mutation that is TAAA to T, but when I open IGV to focus on the loci, it shows that they are more than one mutation, in fact, it's far more than one mutation.
```

The VCF for DeepVariant does not report every single variant present in the reads, it reports the candidate positions which pass the minimum support (as @pgrosu mentioned). So you should see that the other possible variants in the read don't make the threshold required to generate a support.

DeepVariant is operating from an assumption of a diploid organism, if you want to try to do things like detect subclonal variants at lower allele frequencies, that would be good to know, as there would be different recommendations we would make.

**Comment by observer2735** [comment]
Hi,

I'm sorry for the late reply. I didn't have work yesterday and couldn't conduct the experiment. Thank you very much for the detailed suggestions you provided.

I have observed that Paul provided very detailed suggestions regarding the steps he mentioned. I will try them out today and provide feedback here.

My research top is about short tandem repeat in DNA, for example, in human reference gene hg 19 chr 2:47641559-47641586,
it has following base sequence:

chr 2:47641559-47641586      CAGGT AAAAAAAAAAAAAAAAAAAAAAAAAAA GGGTT

After search articles about next-generation sequencing, I found that their have so many factors that influence sequencing outout,such as during library construction step, PCR process will cause different repeat times because of polymerase slip. Besides that, during sequencing step,  taking the Illumina sequencer as an example, during each round of cleaning, the base may not cleaned thoroughly or successfully combined with the next round of base; or other wise, a continuous series of repeated bases will influence illumination recognition signal in sequencer, and the weakened light intensity will affect the efficiency of the sequencer in identifying each binding base.

So the above is the background of my use of Deepvariant. In my research topic, remove noise is very important process, because in  somatic cells or cancer cells it's have different repeat times in tandem repeat regions, and I want to call every  indel  from human cells, but their are so many influence factor that change NGS output data so I can't find truth data in human's gene.

Thank you for reading the questions I encountered in my research, I would greatly appreciate it if you could help me,
and wish you a pleasant work and life.

Ji

**Comment by pgrosu** [comment]
Hi Ji,

I understand better what you're trying to do -- glad for Maria's questions and Andrew's comments.  I'm not sure DeepVariant might be optimal for that, as it was designed for germline variant-calling, and these errors are usually cleaned/corrected by other means before they arrive in DeepVariant.  For STR analysis maybe [HipSTR for Illumina](https://github.com/HipSTR-Tool/HipSTR) or [DeepRepeat for Nanopore](https://github.com/WGLab/DeepRepeat) might help as a first pass, but I'm still trying to think a bit more here.  

Regarding DeepVariant, I need think a bit longer about how it might be used as an inference tool given how it is designed.  You can still experiment with what I mentioned to see how it reacts, though it might not be something I would put a lot of confidence until you validate it by other means. 

As you mentioned, keep in mind you need to compare with a truth set you might have to generate in your lab via something like Sanger sequencing with a high-fidelity PCR enzyme.

Sorry if this lead you too far astray, but I wanted to post before you spent too much time.

Let us know in case there are any questions you might have of why and how DeepVariant operates.

Thanks,
Paul

**Comment by observer2735** [comment]
Dear Paul,

Thank you for you suggestions about STR analysis! 

Please do not apologize, as you have indeed helped me a lot and saved me a lot of time. Thank you for providing very professional guidance on Deepvariant.

I am still unable to reach a conclusion on whether deepvariant can be used in some way on logically paired samples, so I will take a look at the HipSTR and deep repeat you provided, which may be helpful for my research.

Thank you very much!

Wich you have a nice day!

Ji

**Comment by pgrosu** [comment]
Dear Ji,

Glad it was helpful -- research can be fun like that during its discovery phases in opening up surprising doors :)  This definitly got me thinking, which I am also thankful for.  I have updated my previous post with the references to the papers on the two programs.

Hope you have a wonderful day as well!
Paul

**Comment by danielecook** [comment]
I will close this issue @observer2735. If there are any further questions please reopen. Thanks.
